services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: planner
      POSTGRES_PASSWORD: plannerpw
      POSTGRES_DB: plannerdb
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://planner:plannerpw@db:5432/plannerdb
    command: sh -c "npx prisma migrate deploy && PGPASSWORD=plannerpw psql -h db -U planner -d plannerdb -f ./docker/init.sql && yarn start"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pg_data:
